server.port=${PORT:8080}
aws.region=${AWS_REGION:eu-north-1}
nordalert.api.polisen.base-url=https://polisen.se
nordalert.api.polisen.events-url=https://polisen.se/api/events
nordalert.api.smhi.warnings-url=https://opendata-download-warnings.smhi.se/ibww/api/version/1/warning.json
nordalert.api.krisinformation.aggregated-feed-url=https://api.krisinformation.se/v2/aggregatedfeed
nordalert.api.scb.counties-url=https://www.scb.se/en/finding-statistics/regional-statistics/regional-divisions/counties-and-municipalities/counties-and-municipalities-in-numerical-order/
nordalert.subscription.table-name=${SUBSCRIPTION_TABLE_NAME:nord-alert-subscriptions}
nordalert.subscription.sender-email=${SUBSCRIPTION_SENDER_EMAIL:no-reply@example.com}
