name: Build and Deploy Backend

permissions:
  contents: read

on:
  push:
    branches: [ main ]

concurrency:
  group: deploy-main
  cancel-in-progress: false

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/nord-alert-backend
    steps:
      - uses: actions/checkout@v4

      - name: Detect backend changes
        id: backend_changed
        shell: bash
        run: |
          if git diff --quiet "$BASE" "$HEAD" -- backend; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi
        env:
          BASE: ${{ github.event.before }}
          HEAD: ${{ github.sha }}

      - name: Compute image tag
        id: img
        shell: bash
        run: |
          if [ "${{ steps.backend_changed.outputs.changed }}" = "true" ]; then
            echo "tag=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"
          else
            echo "tag=latest" >> "$GITHUB_OUTPUT"
          fi

      - name: Set up Docker Buildx
        if: steps.backend_changed.outputs.changed == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: steps.backend_changed.outputs.changed == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        if: steps.backend_changed.outputs.changed == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: |
            ${{ env.IMAGE_REPO }}:latest
            ${{ env.IMAGE_REPO }}:${{ steps.img.outputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Init
        working-directory: terraform
        run: terraform init -input=false

      - name: Terraform Plan
        id: plan
        working-directory: terraform
        env:
          TF_VAR_tenancy_ocid: ${{ secrets.OCI_TENANCY_OCID }}
          TF_VAR_user_ocid: ${{ secrets.OCI_USER_OCID }}
          TF_VAR_fingerprint: ${{ secrets.OCI_FINGERPRINT }}
          TF_VAR_private_key: ${{ secrets.OCI_PRIVATE_KEY }}
          TF_VAR_region: ${{ secrets.OCI_REGION }}
          TF_VAR_compartment_ocid: ${{ secrets.OCI_COMPARTMENT_OCID }}
          TF_VAR_image: ${{ env.IMAGE_REPO }}:${{ steps.img.outputs.tag }}
          TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: terraform
        env:
          TF_VAR_tenancy_ocid: ${{ secrets.OCI_TENANCY_OCID }}
          TF_VAR_user_ocid: ${{ secrets.OCI_USER_OCID }}
          TF_VAR_fingerprint: ${{ secrets.OCI_FINGERPRINT }}
          TF_VAR_private_key: ${{ secrets.OCI_PRIVATE_KEY }}
          TF_VAR_region: ${{ secrets.OCI_REGION }}
          TF_VAR_compartment_ocid: ${{ secrets.OCI_COMPARTMENT_OCID }}
          TF_VAR_image: ${{ env.IMAGE_REPO }}:${{ steps.img.outputs.tag }}
          TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
        run: terraform apply -input=false -auto-approve tfplan

      - name: Show Terraform outputs
        working-directory: terraform
        shell: bash
        run: |
          echo "## Deployment Outputs" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo "- Web URL: $(terraform output -raw web_url)" >> "$GITHUB_STEP_SUMMARY"
          echo "- Public IP: $(terraform output -raw public_ip)" >> "$GITHUB_STEP_SUMMARY"
          echo "- SSH: $(terraform output -raw ssh_example)" >> "$GITHUB_STEP_SUMMARY"
