name: Terraform Lint & Validate (PRs)
permissions:
  contents: read

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: terraform-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tf-ci:
    if: ${{ github.event.pull_request.head.ref != 'main' }}
    runs-on: ubuntu-latest

    # change if your TF lives in a subfolder (e.g., infra/)
    defaults:
      run:
        shell: bash
        working-directory: .

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform fmt (check only)
        run: terraform fmt -check -diff -recursive

      - name: Terraform init (no backend)
        run: terraform init -backend=false -input=false

      - name: Terraform validate
        run: terraform validate -no-color

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: TFLint init
        run: tflint --init

      - name: TFLint (recursive)
        run: tflint -f compact --recursive
